//! G3 byte-exactness acceptance: the Rust signer's output MUST equal `@nimiq/core`
//! (v2.7.0) **byte-for-byte**. The fixtures in `tests/fixtures/g3_signing_fixtures.json`
//! are generated by `scripts/fixtures/gen-fixtures.mjs` from the canonical WASM bindings;
//! this test reproduces each one from the same `(privKey, recipient, value, vsh, testnet)`
//! inputs and asserts equality of `serializeContent`, the single-sig `SignatureProof`, the
//! detached Ed25519 signature, the full 139-byte `rawHex`, the `txHash`, and the
//! user-friendly address round-trip. A subtly-wrong serializer fails here — that is the bar.

use std::sync::Arc;

use serde::Deserialize;

use nimmesh_core::nimiq::address::Address;
use nimmesh_core::nimiq::hex::{bytes_to_hex, hex_to_bytes};
use nimmesh_core::nimiq::signer::{
    AppSigner, EnclaveKey, InMemoryEnclaveKey, KeyOrigin, TransferIntent,
};
use nimmesh_core::nimiq::tx::{signature_proof_single_sig, Transfer};
use nimmesh_core::NetworkId;

#[derive(Deserialize)]
struct Fixtures {
    fixtures: Vec<Fixture>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fixture {
    name: String,
    priv_key_hex: String,
    pub_key_hex: String,
    sender_address_user: String,
    sender_address_raw: String,
    recipient_address_user: String,
    recipient_address_raw: String,
    value: String,
    validity_start_height: u32,
    network_id: u8,
    serialize_content_hex: String,
    signature_hex: String,
    proof_hex: String,
    raw_hex: String,
    tx_hash: String,
}

fn load() -> Vec<Fixture> {
    let json = include_str!("fixtures/g3_signing_fixtures.json");
    let parsed: Fixtures = serde_json::from_str(json).expect("fixtures parse");
    assert!(!parsed.fixtures.is_empty(), "fixtures must be non-empty");
    parsed.fixtures
}

fn array32(hex: &str) -> [u8; 32] {
    hex_to_bytes(hex).unwrap().try_into().unwrap()
}

#[test]
fn rust_signer_is_byte_exact_against_nimiq_core() {
    for f in load() {
        assert_eq!(f.network_id, 5, "{}: fixtures are testnet-only", f.name);

        // --- enclave/key seam: pubkey + address derivation match @nimiq/core ---
        let secret = array32(&f.priv_key_hex);
        let key = InMemoryEnclaveKey::from_secret(&secret);
        assert_eq!(
            bytes_to_hex(&key.public_key()),
            f.pub_key_hex,
            "{}: public key",
            f.name
        );
        let pubkey = array32(&f.pub_key_hex);
        let sender = Address::from_public_key(&pubkey);
        assert_eq!(
            sender.to_hex(),
            f.sender_address_raw,
            "{}: sender raw",
            f.name
        );
        assert_eq!(
            sender.to_user_friendly(),
            f.sender_address_user,
            "{}: sender user-friendly",
            f.name
        );

        // --- address codec round-trips the recipient exactly ---
        let recipient = Address::from_user_friendly(&f.recipient_address_user).unwrap();
        assert_eq!(
            recipient.to_hex(),
            f.recipient_address_raw,
            "{}: recipient raw",
            f.name
        );
        assert_eq!(
            recipient.to_user_friendly(),
            f.recipient_address_user,
            "{}: recipient round-trip",
            f.name
        );

        // --- serializeContent (67 B) is byte-exact ---
        let transfer = Transfer {
            sender,
            recipient,
            value: f.value.parse().unwrap(),
            fee: 0,
            validity_start_height: f.validity_start_height,
            network_id: f.network_id,
        };
        let content = transfer.serialize_content();
        assert_eq!(content.len(), 67, "{}: content len", f.name);
        assert_eq!(
            bytes_to_hex(&content),
            f.serialize_content_hex,
            "{}: serializeContent",
            f.name
        );
        assert_eq!(
            bytes_to_hex(&transfer.tx_hash()),
            f.tx_hash,
            "{}: txHash",
            f.name
        );

        // --- Ed25519 signature (ed25519-dalek == @nimiq/core, deterministic RFC-8032) ---
        let signature: [u8; 64] = key.sign_content(content).try_into().unwrap();
        assert_eq!(
            bytes_to_hex(&signature),
            f.signature_hex,
            "{}: signature",
            f.name
        );

        // --- 98-byte single-sig SignatureProof is byte-exact ---
        let proof = signature_proof_single_sig(&pubkey, &signature);
        assert_eq!(proof.len(), 98, "{}: proof len", f.name);
        assert_eq!(bytes_to_hex(&proof), f.proof_hex, "{}: proof", f.name);

        // --- full 139-byte Basic-format wire blob is byte-exact ---
        let raw = transfer.serialize_basic(&pubkey, &signature);
        assert_eq!(raw.len(), 139, "{}: raw len", f.name);
        assert_eq!(bytes_to_hex(&raw), f.raw_hex, "{}: rawHex", f.name);
    }
}

#[test]
fn app_signer_end_to_end_matches_fixtures() {
    for f in load() {
        let secret = array32(&f.priv_key_hex);
        let signer = AppSigner::new(Arc::new(InMemoryEnclaveKey::from_secret(&secret)));
        assert_eq!(
            signer.address().unwrap(),
            f.sender_address_user,
            "{}: address",
            f.name
        );

        let intent = TransferIntent {
            recipient: f.recipient_address_user.clone(),
            value: f.value.parse().unwrap(),
            validity_start_height: f.validity_start_height,
            network: NetworkId::Testnet,
        };
        let signed = KeyOrigin::sign_transfer(&*signer, &intent).unwrap();
        assert_eq!(signed.raw_hex, f.raw_hex, "{}: AppSigner rawHex", f.name);
        assert_eq!(signed.tx_hash, f.tx_hash, "{}: AppSigner txHash", f.name);
        assert_eq!(
            signed.valid_until_height,
            f.validity_start_height.saturating_add(7200),
            "{}: validity window",
            f.name
        );
    }
}
